title: 'HSUPipeline'
description: 'A pipeline for processing and analyzing single-unit neural data from human subjects.'

remote_theme: hydecorp/hydejack

author:
  social:
    github: HSUPipeline

menu:
  - title:  Home
    url:    /
  - title:  Templates
    url:    /templates/
  - title:  Sorting
    url:    /sorting/
  - title:  Converting
    url:    /converting/
  - title:  Analysis
    url:    /analysis/
  - title:  CodeMap
    url:    /codemap/
  - title:  Projects
    url:    /projects/
  - title:  convnwb
    url:    /convnwb
  - title:  spiketools
    url:    /spiketools
