title: 'HSUPipeline'
description: 'A pipeline for processing and analyzing single-unit neural data from human subjects.'

remote_theme: hydecorp/hydejack

author:
  social:
    github: HSUPipeline
    twitter: TomDonoghue

menu:
  - title:  Home
    url:    /
  - title:  Templates
    url:    /templates/
  - title:  CodeMap
    url:    /codemap/
  - title:  Projects
    url:    /projects/
  - title:  convnwb
    url:    /convnwb
  - title:  spiketools
    url:    /spiketools
